### PR TITLE
[flutter_local_notifications] Handle scheduled notification receiver null notification

### LINKED ISSUE #1929: NullPointerException on long android.app.Notification.when
**Describe the bug**
I've noticed an exception coming up through our android crash monitoring. We are running plugin version `12.0.4` with flutter `3.3.10`.
The issue seems to happen primarily while the app is in the background state. This seems to happen on all versions of android & with no specific device models being effected more than others.

````
Exception java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to write to field 'long android.app.Notification.when' on a null object reference in method 'void com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(android.content.Context, android.content.Intent)'
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4561)
  at android.app.ActivityThread.-$$Nest$mhandleReceiver
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2308)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:240)
  at android.os.Looper.loop (Looper.java:351)
  at android.app.ActivityThread.main (ActivityThread.java:8364)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
Caused by java.lang.NullPointerException: Attempt to write to field 'long android.app.Notification.when' on a null object reference in method 'void com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(android.content.Context, android.content.Intent)'
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (ScheduledNotificationReceiver.java:35)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4545)
````

### PR DESCRIPTION
**Pull request by Fasust**
Fixes #1929

### CODE REVIEW

File: flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java [hunk 1]
```diff
@@ -26,14 +27,24 @@ public void onReceive(final Context context, Intent intent) {
...
       if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
         notification = intent.getParcelableExtra("notification", Notification.class);
       } else {
         notification = intent.getParcelableExtra("notification");
       }
+
+      if (notification == null) {
+        // This means the notification is corrupt
+        FlutterLocalNotificationsPlugin.removeNotificationFromCache(context, notificationId);
+        Log.e("notification", "Failed to parse a notification from  Intent. ID: " + notificationId);
```
Comment (MaikuB) [inline flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java:43]: sorry i just missed that the tag here is normally the name of the file. something i should've caught for the other PR that dealt with exact alarm permissions. will change this one before it's released so thought i'd let you know

Comment (Fasust) [reply flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ScheduledNotificationReceiver.java:43]: Got it :) Thank you
